name: peg_transformer_sample
version: 0.0.1
description: A simple console application.
dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  peg:
    git: https://github.com/luisvt/peg
transformers:
  - peg
  - dart_to_js_script_rewriter